server:
  port: ${PORT:5000}

base-url: /api

spring:
  profiles:
    active:
      ${APP_ENV}
  application:
    name: library

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

springdoc:
  show-login-endpoint: true
  swagger-ui:
    path: /swagger.html